# Generated by Django 4.2.6 on 2023-12-04 22:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EBazaar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection_name', models.CharField(max_length=20)),
                ('image', models.CharField(max_length=100)),
                ('collection_category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='EBazaar.category')),
            ],
        ),
    ]
