# Generated by Django 4.2.6 on 2023-12-05 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EBazaar', '0002_collection'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_image',
            field=models.CharField(default=None, max_length=20),
            preserve_default=False,
        ),
    ]
