# Generated by Django 4.2.6 on 2023-12-05 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EBazaar', '0003_category_category_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_image',
            field=models.CharField(max_length=100),
        ),
    ]
