# Generated by Django 4.2.6 on 2023-12-05 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EBazaar', '0004_alter_category_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='season',
            field=models.CharField(default='NEW SEASON', max_length=20),
            preserve_default=False,
        ),
    ]
