# Generated by Django 4.2.6 on 2023-12-05 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EBazaar', '0005_collection_season'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sizes', models.FloatField()),
                ('colors', models.CharField(max_length=3)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='SKU',
            field=models.CharField(default='ABC', max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.FloatField(default=7.75),
            preserve_default=False,
        ),
    ]
