# Generated by Django 4.2.6 on 2023-12-05 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EBazaar', '0006_product_details_product_sku_product_weight'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sizes', models.FloatField()),
                ('colors', models.CharField(max_length=3)),
                ('images', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Product_Details',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.AddField(
            model_name='product',
            name='details',
            field=models.ManyToManyField(to='EBazaar.product_detail'),
        ),
    ]
