# Generated by Django 4.2.6 on 2023-12-05 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EBazaar', '0007_product_detail_delete_product_details_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_detail',
            name='sizes',
            field=models.CharField(max_length=3),
        ),
    ]
