# Generated by Django 4.2.6 on 2023-12-05 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EBazaar', '0008_alter_product_detail_sizes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='details',
        ),
        migrations.AddField(
            model_name='product',
            name='colors',
            field=models.CharField(choices=[('color1', 'Red'), ('color2', 'Green'), ('color3', 'Blue'), ('color4', 'Yellow')], default='color1', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='images',
            field=models.CharField(default='image/', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='sizes',
            field=models.CharField(choices=[('size1', 'S'), ('size2', 'M'), ('size3', 'L'), ('size4', 'XL')], default='size1', max_length=50),
        ),
        migrations.DeleteModel(
            name='Product_Detail',
        ),
    ]
