# Generated by Django 4.2.6 on 2023-12-05 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EBazaar', '0009_remove_product_details_product_colors_product_images_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='images',
            new_name='image',
        ),
    ]
