# Generated by Django 4.2.6 on 2023-12-05 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EBazaar', '0011_alter_product_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='colors',
            field=models.CharField(choices=[('color1', 'Red'), ('color2', 'Green'), ('color3', 'Blue'), ('color4', 'Yellow')], default='Red', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='sizes',
            field=models.CharField(choices=[('size1', 'S'), ('size2', 'M'), ('size3', 'L'), ('size4', 'XL')], default='S', max_length=50),
        ),
    ]
