# Generated by Django 4.2.6 on 2023-12-05 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EBazaar', '0012_alter_product_colors_alter_product_sizes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_image',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='collection',
            name='collection_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='collection',
            name='image',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='collection',
            name='season',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('status1', 'Processing'), ('status2', 'Shipped'), ('status3', 'Delivered')], default='Processing', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('user1', 'Wholesaler'), ('user2', 'Seller'), ('user3', 'Customer')], default='user3', max_length=50),
        ),
        migrations.AlterField(
            model_name='wholesaler',
            name='company_name',
            field=models.CharField(max_length=50),
        ),
    ]
