# Generated by Django 4.2.6 on 2023-12-05 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EBazaar', '0013_alter_category_category_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='total_amount',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
    ]
