# Generated by Django 4.2.6 on 2023-12-05 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EBazaar', '0014_cart_total_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='colors',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='sizes',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
