# Generated by Django 4.2.6 on 2023-12-05 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EBazaar', '0016_alter_product_colors_alter_product_sizes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='colors',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sizes',
        ),
    ]
